metadata:
  id: "com.example.hello_world"
  name: "Hello World Plugin"
  version: "1.0.0"
  author: "ClassTop Team"
  description: "A simple hello world plugin demonstrating basic plugin structure"
  language: "python"

dependencies:
  classtop_version: ">=2.0.0"

permissions:
  - read:courses
  - emit:events
